// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg9sNyDNY_pUQX4sWsL6BAjpV_4ZEvxaQ',
    appId: '1:114786751346:web:31349aace2a50e1b4703eb',
    messagingSenderId: '114786751346',
    projectId: 'artlink-56f38',
    authDomain: 'artlink-56f38.firebaseapp.com',
    storageBucket: 'artlink-56f38.appspot.com',
    measurementId: 'G-JCT2DX333S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpAtjyRA-CcXBm61ADe1i9BcinQIKTIEM',
    appId: '1:114786751346:android:f12521e1939052674703eb',
    messagingSenderId: '114786751346',
    projectId: 'artlink-56f38',
    storageBucket: 'artlink-56f38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmpP9-iTrZzyhAQsPWLLtr7uTNYeI2us',
    appId: '1:114786751346:ios:244b7dd152cc190e4703eb',
    messagingSenderId: '114786751346',
    projectId: 'artlink-56f38',
    storageBucket: 'artlink-56f38.appspot.com',
    iosBundleId: 'com.example.ashlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZmpP9-iTrZzyhAQsPWLLtr7uTNYeI2us',
    appId: '1:114786751346:ios:244b7dd152cc190e4703eb',
    messagingSenderId: '114786751346',
    projectId: 'artlink-56f38',
    storageBucket: 'artlink-56f38.appspot.com',
    iosBundleId: 'com.example.ashlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg9sNyDNY_pUQX4sWsL6BAjpV_4ZEvxaQ',
    appId: '1:114786751346:web:3cd40d7a6571dd5e4703eb',
    messagingSenderId: '114786751346',
    projectId: 'artlink-56f38',
    authDomain: 'artlink-56f38.firebaseapp.com',
    storageBucket: 'artlink-56f38.appspot.com',
    measurementId: 'G-P5RH6PWPQQ',
  );
}
